/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RodRodIdRouteImport } from './routes/rod.$rodId'
import { Route as CheckoutRodIdRouteImport } from './routes/checkout.$rodId'

const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RodRodIdRoute = RodRodIdRouteImport.update({
  id: '/rod/$rodId',
  path: '/rod/$rodId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRodIdRoute = CheckoutRodIdRouteImport.update({
  id: '/checkout/$rodId',
  path: '/checkout/$rodId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/checkout/$rodId': typeof CheckoutRodIdRoute
  '/rod/$rodId': typeof RodRodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/checkout/$rodId': typeof CheckoutRodIdRoute
  '/rod/$rodId': typeof RodRodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/checkout/$rodId': typeof CheckoutRodIdRoute
  '/rod/$rodId': typeof RodRodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/collection' | '/checkout/$rodId' | '/rod/$rodId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/collection' | '/checkout/$rodId' | '/rod/$rodId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collection'
    | '/checkout/$rodId'
    | '/rod/$rodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionRoute: typeof CollectionRoute
  CheckoutRodIdRoute: typeof CheckoutRodIdRoute
  RodRodIdRoute: typeof RodRodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rod/$rodId': {
      id: '/rod/$rodId'
      path: '/rod/$rodId'
      fullPath: '/rod/$rodId'
      preLoaderRoute: typeof RodRodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$rodId': {
      id: '/checkout/$rodId'
      path: '/checkout/$rodId'
      fullPath: '/checkout/$rodId'
      preLoaderRoute: typeof CheckoutRodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionRoute: CollectionRoute,
  CheckoutRodIdRoute: CheckoutRodIdRoute,
  RodRodIdRoute: RodRodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
